version: '3.8'

services:
  pg:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: px
      POSTGRES_PASSWORD: px
      POSTGRES_DB: px
    ports:
      - "15432:5432"
    volumes:
      - ./vols/pgdb:/var/lib/postgresql/data

  px:
    image: ghcr.io/payamax/api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    depends_on:
      - pg
    environment:
      ConnectionString__Host: pg
      ConnectionString__Port: 5432
      ConnectionString__Username: px
      ConnectionString__Database: px
      ConnectionString__Password: px
    ports:
      - "5260:8080"
  # wt:
  #   environment:
  #     - WATCHTOWER_DEBUG=true
  #   image: containrrr/watchtower:1.5.3
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - $HOME/.docker/config.json:/config.json
  #   command: --label-enable --interval 30